import HeaderBar from "@/components/HeaderBar"
import FooterBar from "@/components/FooterBar"
import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"

import styles from '@/styles/ErrorPage.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function error() {
    return (
      <>
        <Head>
          <title>ERROR 404</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={inter.className}>
          <HeaderBar />
          <div className={styles.errorDiv}>
            <div>
              <Image src="/img/jambogg.png" width="600" height="225" />
              <p className={styles.errorText}> 
                {`Error 404! You've gotten lost...`}
              </p>
            </div>
          </div>
          <FooterBar />
        </main>
      </>
    )
  }