import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import HeaderBar from '@/components/HeaderBar'
import FooterBar from '@/components/FooterBar'
import SearchBar from '@/components/SearchBar'
import styles from '@/styles/HomePage.module.css'
import ToolMenu from '@/components/ToolMenu'
import RouterBar from '@/components/RouterBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Jambo.GG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <RouterBar />
        <div className={styles.titleImage}>
          <Image src="/img/jambogg.png" width="600" height="225" />
        </div>
        <SearchBar />
        <FooterBar />
      </main>
    </>
  )
}
